### ISSUE TITLE
[Question] What is the projected timeline for SkiaSharp.Extended to move to GA

### ISSUE THREAD

**Issue by TKwakernaak** [mono/SkiaSharp.Extended#178] opened 2023-08-18 06:13 UTC
Hi,

It's great to have a tool to create Lottie animations in MAUI, Thanks! I'm curious about the projected timeline for the package's transition to General Availability (GA). Can you give us some insight in that?

Thank you for your time and efforts!

Kind regards

**Comment by mattleibow** [comment] 2024-04-05 22:53
Duplicate of https://github.com/mono/SkiaSharp.Extended/issues/249

**Closed by mattleibow** 2024-04-05 22:53 UTC
Labels: question
