### ISSUE TITLE
Cannot render properly

### ISSUE THREAD

**Issue by claunia** [mono/SkiaSharp.Extended#51] opened 2018-09-09 10:04 UTC
Tried with several SVGs:

[Sample svg](https://raw.githubusercontent.com/mono/SkiaSharp.Extended/master/SkiaSharp.Extended.Svg/samples/SkiaSharpDemo/SkiaSharpDemo/images/logos.svg)
![image](https://user-images.githubusercontent.com/1234569/45263343-85686f80-b41f-11e8-9e8f-aef5689577cc.png)

Gets rendered as:
![image](https://user-images.githubusercontent.com/1234569/45263351-acbf3c80-b41f-11e8-8c0a-b0d12119fb09.png)

And
[Sample svg](https://upload.wikimedia.org/wikipedia/commons/e/ed/Compact_Disc_wordmark.svg)
![image](https://user-images.githubusercontent.com/1234569/45263367-daa48100-b41f-11e8-96a5-90160a47aef5.png)

Is completely invisible.

Code:
```
            SKSvg                svg      = new SKSvg();
            SKEncodedImageFormat skFormat = SKEncodedImageFormat.Png;
            svg.Load(svgStream);
            //SKRect   svgSize   = svg.Picture.CullRect;
            float canvasMin = Math.Min(svg.Picture.CullRect.Width, svg.Picture.CullRect.Height);
            float svgMax = Math.Max(svg.Picture.CullRect.Width, svg.Picture.CullRect.Height);
            float scale = canvasMin / svgMax;
            var matrix = SKMatrix.MakeScale(scale, scale);
            SKBitmap bitmap    = new SKBitmap((int)svg.Picture.CullRect.Width, (int)svg.Picture.CullRect.Height);
            SKCanvas canvas    = new SKCanvas(bitmap);
            canvas.DrawPicture(svg.Picture, ref matrix);
            canvas.Flush();
            SKImage      image = SKImage.FromBitmap(bitmap);
            SKData       data  = image.Encode(skFormat, 100);
            MemoryStream outMs = new MemoryStream();
            data.SaveTo(outMs);
            cachedRender = outMs.ToArray();
            base.Image   = new Bitmap(cachedRender);
            FileStream foo = new FileStream("/mnt/datos/foo.png", FileMode.Create);
            foo.Write(cachedRender, 0, cachedRender.Length);
            foo.Close();
```

**Comment by mattleibow** [comment] 2018-10-04 12:37
Closing this as it is a duplicate of #42 fixed in #44

**Closed by mattleibow** 2018-10-04 12:37 UTC
Labels: area-SkiaSharp.Extended.Svg, bug, duplicate
