### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rbhavsar2022** [mono/SkiaSharp.Extended#135] opened 2022-08-04 10:38 UTC
Issue with SkiaSharp.Extended.UI.Maui Version=2.0.0-preview.59, When using our nuget package Esri.ArcGISRuntime.Maui Version=100.14.1-preview3

/Users/xxxx/.nuget/packages/skiasharp.nativeassets.ios/2.88.1-preview.91/buildTransitive/net6.0-ios13.6/SkiaSharp.NativeAssets.iOS.targets(9,9): Error MSB4096: The item "/Users/xxxx/.nuget/packages/esri.arcgisruntime.runtimes.ios/100.14.1/buildTransitive/net6.0-ios13/../../framework/iossimulator-x64/native/ArcGIS-simx64.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename". In order to use this metadata, either qualify it by specifying %(NativeReference.FrameworkFilename), or ensure that all items in this list define a value for this metadata. (MSB4096)

**Comment by mattleibow** [comment] 2022-08-05 07:23
Duplicate of #1879

**Closed** 2022-08-05 07:24 UTC
Labels: bug
