### ISSUE TITLE
SVG colors confused in SkiaSharp.Svg 1.60.0

### ISSUE THREAD

**Issue by charlesroddie** [mono/SkiaSharp.Extended#42] opened 2018-05-30 10:15 UTC
SkiaSharp.Svg 1.60.0 gets colors confused, with text color sometimes taken from the colors of other elements. 1.59.1 is OK.

[SVGColors.zip](https://github.com/mono/SkiaSharp.Extended/files/2053503/SVGColors.zip)

Should look like:

![image](https://user-images.githubusercontent.com/19760720/40714152-b64be24c-63f9-11e8-955a-ddb32101566e.png)

But looks like this in 1.60.0, as some text color is taken from other white text:

![image](https://user-images.githubusercontent.com/19760720/40714265-11f9a548-63fa-11e8-9e5f-87b975177c91.png)

Tested using SkiaSharp / SkiaSharp.Views.Forms 1.60.0 and 1.60.1

**Comment by AxelUser** [comment] 2018-06-05 18:46
Seems like something is wrong with path's default fill. Temporal measure before cure is to set to all groups their colors:
```<g style="clip-path:url(#SVGID_36_);fill:black;">```.

**Comment by daniel-luberda** [comment] 2018-06-09 17:19
This should be fixed with: https://github.com/mono/SkiaSharp.Extended/pull/38/commits/9cf03c4c03bfbcdcc1d60992ba7a69aba1d3010e#diff-54eeb522f1f0baf1f0fb5e1d63c39ba4R889

**Comment by AxelUser** [comment] 2018-06-10 08:03
@daniel-luberda Hi! Your fixes are quite reasonable, but I checked your fork's demo with image in issue and result is the same.
Seems like problem is caused by preserving (cascading) fill color here: https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/source/SkiaSharp.Extended.Svg.Shared/SKSvg.cs#L871
```csharp
if (string.IsNullOrEmpty(fill))
{
    // no change
}
```

It may be reproduced if you in SkiaSharpDemo/images/logos.svg in path with id `microsoft-text` remove ` style="fill:#727272"`. This will result in preserving blue fill color from previous logo (Xamarin) in caption "Microsoft". Example is somewhere below.

If you pass fills to all groups or paths/rects/etc, there is no problem. May be it is some kind of fail in Adobe Illustrator. But somehow web-browsers support cascading correctly.

![image](https://user-images.githubusercontent.com/7935489/41199600-0f9b9970-6cae-11e8-9b75-e8d43f6e97fe.png)

**Comment by AxelUser** [comment] 2018-06-10 19:15
Fixed in #44 
![image](https://user-images.githubusercontent.com/7935489/41205414-7766e6c8-6d0c-11e8-8982-7182abf779a9.png)

**Closed** 2018-10-25 20:28 UTC
Labels: area-SkiaSharp.Extended.Svg, bug
