### ISSUE TITLE
[BUG]  Valid Lottie file not shown

### ISSUE THREAD

**Issue by twsl** [mono/SkiaSharp.Extended#158] opened 2022-12-31 02:29 UTC
**Description**

Used the following Lottie file: https://lottiefiles.com/36895-healthy-or-junk-food
Seems to be related to the usage of the base64 encoded image data. Other Lottie files work just fine.

**Code**

```xaml
<!--  or use local file name  -->
<skia:SKLottieView
                HeightRequest="200"
                HorizontalOptions="Center"
                RepeatCount="-1"
                Source="https://assets4.lottiefiles.com/packages/lf20_tll0j4bb.json"
                WidthRequest="200" />
```

**Expected Behavior**

Shows the animation.

**Actual Behavior**

Does not show anything at all.

**Basic Information**

- Version with issue:  2.0.0-preview.61
- Last known good version:  none
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android: 21
- Target Devices:   
  - Device OnePlus 10 Pro
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by Ricardo-Fernandes-Cavalcante** [comment] 2023-04-06 16:08
any idea how to fix this?

**Comment by thomaskaelin** [comment] 2023-04-28 13:27
Having the same issue right now. Any workarounds for this? Or is there another alternative for integrating Lottie other than SkiaSharp?

**Comment by mattleibow** [comment] 2023-09-01 18:51
Duplicate of https://github.com/mono/SkiaSharp.Extended/issues/169

**Closed by mattleibow** 2023-09-01 18:51 UTC
Labels: bug

**Comment by nathenxbrewer** [comment] 2023-09-21 15:08
> Duplicate of #169

This is not a duplicate. #169 is referencing the ability to put .png paths inside of the lottie json. OP is referencing an issue where base64 PNGs are not rendering. I am having the same issue while using base64 in my lottie file.

**Comment by mattleibow** [comment] 2023-09-21 19:19
I think it is a duplicate as none of the image in the json are supported - files or embedded. This is a feature that is enabled in the internal builder that is not yet exposed in SkiaSharp.

I'll add a comment in the other issue just so I can test both.

**Comment by nathenxbrewer** [comment] 2023-09-21 19:21
> I think it is a duplicate as none of the image in the json are supported - files or embedded. This is a feature that is enabled in the internal builder that is not yet exposed in SkiaSharp.
> 
> I'll add a comment in the other issue just so I can test both.

Ok, that works, thanks. So you're saying that this fix may be coming soon?

**Comment by mattleibow** [comment] 2023-09-21 19:28
Ah, sorry for false hope. Not sure yet. The real issue is tracked here and lots of people are asking for it: https://github.com/mono/SkiaSharp/issues/2173

**Comment by mattleibow** [comment] 2023-09-22 16:45
This PR will get us to the happy place: https://github.com/mono/SkiaSharp/pull/2630
